title: Daedalus's dev
description: Bienvenue chez Flûte Corp. !
github:
  repository_url: https://daedalusdev.github.io
projects:
  - name: Bar.js
    url: https://github.com/DaedalusDev/bar.js
    description: Partagez efficacement l'addition avec vos amis !
    img: http://bar.nexk.fr/src/img/favicon/bar.svg
  - name: Bar.php
    url: https://github.com/DaedalusDev/bar.php
    description: Profitez d'une solide API REST pour gérer vos articles Bar.js
    img: http://bar.nexk.fr/src/img/favicon/bar.svg
  - name: FluxManager
    url: https://github.com/DaedalusDev/FluxManager
    description: Administrez et visualisez le flux de donnée de votre application.
  - name: FluxManagerApi
    url: https://github.com/DaedalusDev/FluxManagerApi
    description: Api de mise en persistance des information de FluxManager
  - name: Capeloï
    url: https://github.com/DaedalusDev/capeloi
    description: Application "clé en main" pour une gestion de stock efficace
  - name: Magasin.vue
    url: https://github.com/DaedalusDev/Magasin.vue
    description: Application "clé en main" pour gérer une boutique




